"use client";
import React, { useState } from "react";
import FormField from "../components/FormField";
import { getRandomPrompt } from "../utils";
import Image from "next/image";
import { createPost, generateImage } from "@/lib/action";
import { useRouter } from "next/navigation";
type GeneratedImage = {
    image: {
        img: string;
        prompt: string;
    };
};
const CreateImage = () => {
    const router = useRouter();
    const [form, setForm] = useState({
        name: "",
        prompt: "",
        image: "",
    });
    const [generatingImg, setGeneratingImg] = useState(false);
    const [sharingImg, setSharingImg] = useState(false);
    const handleSubmit = async () => {
        setSharingImg(true);
        const post = await createPost(form);
        setSharingImg(false);
        router.push("/");
    };
    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setForm({ ...form, [e.target.name]: e.target.value });
    };
    const handleSurpriseMe = () => {
        const randomPrompt = getRandomPrompt(form.prompt);

        setForm({ ...form, prompt: randomPrompt });
    };

    const generateImg = async () => {
        setGeneratingImg(true);
        const images = (await generateImage(
            form.prompt as string
        )) as GeneratedImage;
        if (images) {
            setForm({
                ...form,
                image: `data:image/jpeg;base64,${images.image.img}`,
            });
        }
        setGeneratingImg(false);
    };

    return (
        <section className='max-w-7xl mx-auto'>
            <h1 className='font-extrabold text-[#222328] text-4xl w-fit mx-auto'>
                Let Your Imagination turn into Reality.
            </h1>
            <p className='mt-2 text-[#666e75] text-sm max-w-[500px] lg:max-w-full lg:flex lg:justify-center lg:items-center'>
                Create imaginative and visually stunning images generated by
                DALL-E AI and share them to community
            </p>
            <form className='mt-16 max-w-3xl mx-auto' onSubmit={handleSubmit}>
                <div className='flex flex-col gap-5'>
                    <FormField
                        labelName='Your Name'
                        type='text'
                        name='name'
                        placeholder='John Doe'
                        value={form.name}
                        handleChange={handleChange}
                    />

                    <FormField
                        labelName='Prompt'
                        type='text'
                        name='prompt'
                        placeholder='A photo of a white fur monster standing in a purple room'
                        value={form.prompt}
                        handleChange={handleChange}
                        isSurpriseMe
                        handleSurpriseMe={handleSurpriseMe}
                    />
                    <div className='relative bg-gray-50 border border-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
                        {form.image ? (
                            <Image
                                src={form.image}
                                alt={form.prompt}
                                fill
                                className='w-full h-full object-contain'
                            />
                        ) : (
                            <Image
                                src='/assets/preview.png'
                                alt='Preview'
                                fill
                                className='w-9/12 h-[75%] object-contain opacity-50'
                            />
                        )}
                        {generatingImg && (
                            <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,.5)] rounded-lg'>
                                <svg
                                    aria-hidden='true'
                                    className='inline w-10 h-10 mr-2 text-gray-200 animate-spin fill-[#6469ff]'
                                    viewBox='0 0 100 101'
                                    fill='none'
                                    xmlns='http://www.w3.org/2000/svg'
                                >
                                    <path
                                        d='M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z'
                                        fill='currentColor'
                                    />
                                    <path
                                        d='M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z'
                                        fill='currentFill'
                                    />
                                </svg>
                            </div>
                        )}
                    </div>
                </div>
                <div className='mt-5 flex gap-5 w-full'>
                    <button
                        type='button'
                        disabled={generatingImg || sharingImg}
                        onClick={generateImg}
                        className='text-green-700 font-semibold transition-all duration-300 border border-green-700 hover:text-white  hover:bg-green-700 rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center tracking-wider active:bg-white active:text-green-950 '
                    >
                        {generatingImg ? "Generating..." : "Generate"}
                    </button>
                </div>
                <div className='mt-10'>
                    <p className='mt-2 text-[#666e75] text-sm'>
                        Once you have create the image you want ,you can share
                        it with othre in the community
                    </p>
                    <button
                        type='button'
                        onClick={handleSubmit}
                        disabled={generatingImg || sharingImg}
                        className='mt-3 font-semibold transition-all duration-300 border text-white border-[#6469ff] bg-[#6469ff] rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center tracking-wider active:bg-white  '
                    >
                        {sharingImg ? "Sharing..." : "Share with the Community"}
                    </button>
                </div>
            </form>
        </section>
    );
};

export default CreateImage;
